package web

import (
	"bytes"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"net/http"
	"time"
)

// The compiled stylesheet, built from internal/web/assets by `make css` and committed. It is
// embedded rather than read from disk so the binary stays the only thing a deployment needs,
// and committed rather than built in the image so `go build ./...` works for a contributor
// who has never heard of Tailwind. docs/ui.md has the whole arrangement.
//
//go:embed static/app.css
var stylesheet []byte

// stylesheetURL is the path the stylesheet is served from, with a digest of its own contents
// in the name.
//
// The alternative is a fixed path and a short cache lifetime, which trades a stale stylesheet
// after an upgrade against a revalidation on every page view. A digest in the name has
// neither problem: the URL changes when the bytes change, so the response can be cached for
// as long as a browser is willing to and an upgrade is picked up on the next page load
// without anybody having to reason about it.
var stylesheetURL = "/static/app." + digest(stylesheet) + ".css"

// The script, hand-written and served byte for byte. Everything in static/ is what the
// browser receives; the stylesheet beside it happens to be generated by `make css` and this
// is not, which is why there is no build step to run before `go build ./...` and no second
// copy of this file anywhere in the tree. Edit it here.
//
//go:embed static/app.js
var script []byte

// scriptURL is the path the script is served from, addressed by its own contents for the
// same reason the stylesheet is: an upgrade changes the URL, so a year-long cache lifetime
// cannot serve yesterday's behaviour against today's markup.
var scriptURL = "/static/app." + digest(script) + ".js"

func digest(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])[:12]
}

// serveStylesheet answers with the compiled CSS.
//
// http.ServeContent rather than a plain Write: it brings conditional requests, range requests
// and the Last-Modified handling with it, so a browser that already has the file gets a 304
// instead of the body. The modification time is zero because there isn't one — an embedded
// file has no timestamp, and inventing the process start time would make every restart look
// like a change.
func (s *Server) serveStylesheet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/css; charset=utf-8")
	// Safe precisely because the name contains the digest: a different stylesheet is a
	// different URL, so nothing cached under this one can ever be wrong.
	w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	w.Header().Set("ETag", `"`+digest(stylesheet)+`"`)
	http.ServeContent(w, r, "app.css", time.Time{}, bytes.NewReader(stylesheet))
}

// serveScript answers with the script, on the same terms as the stylesheet above.
//
// The content type is load-bearing twice over: a browser refuses to execute a script served
// as anything else once X-Content-Type-Options is nosniff, which it is on every response
// here — and a page whose enhancement silently did not load is meant to still work, so that
// refusal would show up as nothing at all rather than as an error.
func (s *Server) serveScript(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	w.Header().Set("ETag", `"`+digest(script)+`"`)
	http.ServeContent(w, r, "app.js", time.Time{}, bytes.NewReader(script))
}
