package mcp

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/tfyl/mailroom/internal/aggregate"
	"github.com/tfyl/mailroom/internal/blob"
	"github.com/tfyl/mailroom/internal/grant"
	"github.com/tfyl/mailroom/internal/held"
	"github.com/tfyl/mailroom/internal/mail"
	"github.com/tfyl/mailroom/internal/user"
)

// ProviderFactory builds a live provider for an account, unsealing its stored credential.
type ProviderFactory interface {
	For(ctx context.Context, acct mail.Account) (mail.Provider, error)
}

// AccountLister resolves a linked mailbox by id, scoped to its owner.
//
// The owner comes from the grant rather than from the request, so a token cannot reach a
// mailbox belonging to anyone but the user who approved it — even by naming a valid id.
type AccountLister interface {
	Account(ctx context.Context, owner user.ID, id mail.AccountID) (mail.Account, error)
}

type Tools struct {
	gate      *grant.Gate
	providers ProviderFactory
	accounts  AccountLister
	blobs     *blob.Store

	sends      SendCounter
	sendLimit  int
	sendWindow time.Duration

	// holds is where a privileged call goes when the grant's mode says it is not to be
	// performed, and holdURL is the page its owner answers it on. Both are set together;
	// see WithHoldQueue for what happens when they are not.
	holds   *held.Queue
	holdURL string
}

func NewTools(gate *grant.Gate, providers ProviderFactory, accounts AccountLister) *Tools {
	return &Tools{gate: gate, providers: providers, accounts: accounts}
}

// WithBlobs gives the tools somewhere to put attachment bytes.
//
// Optional in the type and never optional in a real server: without it mail_get_attachment
// has nowhere to write and mail_upload_url has nothing to hand out, and both say so rather
// than falling back to putting bytes in the conversation. The fallback is what this whole
// change removes.
func (t *Tools) WithBlobs(store *blob.Store) *Tools {
	t.blobs = store
	return t
}

// WithSendLimit caps outbound sends per grant inside a rolling window. Configured at startup
// rather than optional at call time: a send path with no limit is one bad inference away
// from mailing every contact the mailbox has.
func (t *Tools) WithSendLimit(counter SendCounter, limit int, window time.Duration) *Tools {
	t.sends, t.sendLimit, t.sendWindow = counter, limit, window
	return t
}

// WithHoldQueue gives the tools somewhere to put a privileged call that a grant's mode says
// must wait for its owner, and the address of the page they answer it on.
//
// Optional in the type and not optional in a real server. A grant in `hold` mode whose tools
// have no queue is the one arrangement where a strict setting could quietly become a loose
// one, so the holdable handlers refuse outright rather than fall through and perform: see
// hold below. That is the whole of "client does not support this, so we proceeded" being
// designed out — the mode is enforced here or the call does not happen.
func (t *Tools) WithHoldQueue(q *held.Queue, publicURL string) *Tools {
	t.holds, t.holdURL = q, strings.TrimSuffix(publicURL, "/")+"/held"
	return t
}

// Register adds the tools this grant may call. Input schemas are generated by the SDK from
// the argument types below, so the schema a client sees cannot drift from what the handler
// actually parses.
//
// The grant decides two things here, and they are not the same kind of thing. Which tools
// exist at all is its capabilities, and that is enforcement: a tool that is not registered
// cannot be called. What each one says is its mode, and that is steering: the text a model
// reads before deciding. The descriptions come from steering.go, which is written to be
// honest about that distinction — and, under `hold`, to tell a client that its send is going
// to be queued rather than delivered, because a client that reports "sent" on the strength of
// a successful call has told its user something false.
//
// The mode is read from the grant, and the grant is re-read from the store on every request.
// There is no path from a tool call to it: see mode_test.go, which drives every registered
// tool with a mode argument attached and reads the stored grant back afterwards.
//
// Every tool goes through tool(), which attaches the annotations for its name. That is a
// third thing the client is told, and the only one it acts on without reading: annotations.go
// holds the table and the reasoning, including why they do not vary with the mode when the
// descriptions do.
func (t *Tools) Register(srv *mcp.Server, g *grant.Grant) {
	// Discovery needs no capability. Knowing which mailboxes a grant reaches is not
	// privileged; it is a prerequisite for using the grant sensibly.
	mcp.AddTool(srv, tool("mail_accounts", describe("mail_accounts", g.Mode)), t.handleAccounts)

	if g.Caps.Has(mail.CapRead) {
		mcp.AddTool(srv, tool("mail_search",
			"Search mail across one or more mailboxes, newest first. Returns a "+
				"per-account status block; check it before concluding that no mail matched."),
			t.handleSearch)

		mcp.AddTool(srv, tool("mail_get_message",
			"Fetch one message in full, including body and attachment manifest."),
			t.handleGetMessage)

		mcp.AddTool(srv, tool("mail_get_thread",
			"Fetch a whole conversation in order. Check `derived`: when true the "+
				"grouping was inferred from headers rather than reported by the provider."),
			t.handleGetThread)
	}

	// mail_labels serves two capabilities, so either one is enough to be offered it: listing
	// labels is reading, and creating or deleting one changes the mailbox. Registering it
	// under `read` alone left a grant holding `labels` without `read` with no label tool at
	// all, though the consent screen had offered exactly that combination.
	if g.Caps.Has(mail.CapRead) || g.Caps.Has(mail.CapLabels) {
		mcp.AddTool(srv, tool("mail_labels",
			"List labels, or create and delete them. Listing needs the `read` "+
				"capability; creating and deleting need `labels`."),
			t.handleLabels)
	}

	if g.Caps.Has(mail.CapAttachments) {
		mcp.AddTool(srv, tool("mail_get_attachment",
			"Get an attachment as a short-lived download URL. The file itself does "+
				"not come back through this conversation: you get a link, and you or the user "+
				"fetch it with an ordinary HTTP GET. The link needs no header — it carries its "+
				"own signature — expires within minutes, and stops working the moment the grant "+
				"behind it is revoked, so fetch it promptly and do not store it. Set `inline` "+
				"only for a small text file whose contents you actually have to read; that is "+
				"capped and refuses anything that is not text. "+
				"If you cannot make HTTP requests of your own, you are not stuck: give the URL "+
				"to the person you are working with, say what the file is and when the link "+
				"expires, and treat that as the finished job rather than a failure."),
			t.handleGetAttachment)
	}

	// Minting an upload URL is gated on being able to compose rather than on `attachments`,
	// which means downloading mail. Bytes staged here can only ever be attached to a message,
	// so the permission that reaches them is the one that could attach them: a grant that
	// cannot draft or send has no use for an upload URL, and should not be able to write to
	// this server's disk to find out.
	if g.Caps.Has(mail.CapDraft) || g.Caps.Has(mail.CapSend) {
		mcp.AddTool(srv, tool("mail_upload_url",
			"Get a short-lived URL to upload a file you want to attach to a message. "+
				"Three steps, in order: call this to get `upload_url` and `blob_id`; PUT the "+
				"file's bytes to `upload_url` as the raw request body, with no authorization "+
				"header; then pass {\"blob_id\": \"...\"} in the `attachments` list of "+
				"mail_draft or mail_send. The bytes never pass through this conversation, so "+
				"this is the way to attach anything larger than a couple of megabytes, or "+
				"anything you hold as a local file. The URL works once and expires within "+
				"minutes; the blob_id lasts longer, and both deadlines come back with it. "+
				"Step two is yours to perform. If you cannot make HTTP requests of your own, "+
				"either attach the file inline as `content_base64` instead — under 2 MiB, and "+
				"only if you hold the bytes — or hand `upload_url` to the person you are "+
				"working with, ask them to PUT the file to it, and wait until they say it is "+
				"done before you name the blob_id."),
			t.handleUploadURL)
	}

	// mail_draft serves two capabilities the way mail_labels does, so either one is enough to
	// be offered it: `draft` writes a draft and `discard` removes one. Registering it under
	// `draft` alone would leave a grant holding `discard` without it with no way to delete a
	// draft, though the consent screen offers exactly that combination.
	if g.Caps.Has(mail.CapDraft) || g.Caps.Has(mail.CapDiscard) {
		mcp.AddTool(srv, tool("mail_draft", describe("mail_draft", g.Mode)), t.handleDraft)
	}

	if g.Caps.Has(mail.CapSend) {
		mcp.AddTool(srv, tool("mail_send", describe("mail_send", g.Mode)), t.handleSend)
	}

	if g.Caps.Has(mail.CapLabels) {
		mcp.AddTool(srv, tool("mail_modify", describe("mail_modify", g.Mode)), t.handleModify)
	}

	if g.Caps.Has(mail.CapDestructive) {
		mcp.AddTool(srv, tool("mail_trash", describe("mail_trash", g.Mode)), t.handleTrash)
	}

	if g.Caps.Has(mail.CapFilters) {
		mcp.AddTool(srv, tool("mail_filters", describe("mail_filters", g.Mode)), t.handleFilters)
	}

	if g.Caps.Has(mail.CapSettings) {
		mcp.AddTool(srv, tool("mail_settings", describe("mail_settings", g.Mode)), t.handleSettings)
	}

	registerPrompts(srv, g)
}

// --- mail_accounts ---

type accountsArgs struct{}

type accountInfo struct {
	Alias    string   `json:"alias"`
	Address  string   `json:"address"`
	Provider string   `json:"provider"`
	Status   string   `json:"status"`
	Granted  []string `json:"granted"`
	Supports []string `json:"provider_supports"`
	Quirks   []string `json:"quirks"`
}

// handleAccounts reports three separate facts per mailbox: what the grant permits, what the
// provider can do at all, and behavioural quirks. Collapsing the first two would leave a
// caller unable to tell "you were not granted this" from "this mailbox cannot do it", which
// are different problems with different fixes.
func (t *Tools) handleAccounts(ctx context.Context, _ *mcp.CallToolRequest, _ accountsArgs) (*mcp.CallToolResult, any, error) {
	g, err := requireGrant(ctx)
	if err != nil {
		return nil, nil, err
	}

	var infos []accountInfo
	var aliases []string

	for _, id := range g.Accounts {
		acct, err := t.accounts.Account(ctx, g.OwnerID, id)
		if err != nil {
			continue
		}

		info := accountInfo{
			Alias:    acct.Alias,
			Address:  acct.Address,
			Provider: string(acct.Provider),
			Status:   string(acct.Status),
			Granted:  g.Caps.Strings(),
			Quirks:   []string{},
		}

		// Provider capability needs a live provider. When one cannot be built — expired
		// credentials, most often — say so through the status rather than reporting an empty
		// capability set, which would read as "this mailbox can do nothing".
		if p, err := t.providers.For(ctx, acct); err == nil {
			info.Supports = p.Capabilities().Strings()
			for _, q := range p.Quirks() {
				info.Quirks = append(info.Quirks, string(q))
			}
		} else {
			info.Status = string(mail.StatusNeedsReauth)
			info.Supports = []string{}
		}

		// Discovery is a call like any other, and it unseals a credential per mailbox to ask
		// what that mailbox can do. One row per account, as an aggregated read writes, rather
		// than the nothing this used to write.
		//
		// No capability, because it spends none. That is a fact about discovery rather than a
		// missing value, and the page renders it as one.
		if err := t.auditRead(ctx, g, grant.Audit{
			AccountID: acct.ID, Tool: "mail.accounts",
		}, nil); err != nil {
			return toolError(err), nil, nil
		}

		infos = append(infos, info)
		aliases = append(aliases, acct.Alias)
	}

	// The mode, said again in the result. The tool descriptions carry it too, but a client
	// that cached its tool list at connection time and a client that re-reads it on every
	// call are both real, and this is the call every client is told to make first. `enforced`
	// is the honest half: two of the three modes are wording, and only one of them is
	// something this server will refuse on.
	mode := g.Mode.Resolved()
	modeInfo := map[string]any{
		"name":     string(mode),
		"means":    mode.Summary(),
		"enforced": mode.Enforced(),
	}
	if mode.Holds() {
		modeInfo["held_tools"] = []string{
			"mail_send", "mail_trash (trash and delete)", "mail_filters (create and delete)",
			"mail_settings (set_vacation)",
		}
		modeInfo["approved_at"] = t.holdURL
	}

	// default_scope stays a list of bare aliases. It is not a description of the mailboxes —
	// the accounts block above is, and carries each address beside its alias — it is the
	// selector an omitted `account` is equivalent to, and a caller copying an entry of it
	// into the next call has to land on a mailbox. A rendered "alias - address" label would
	// not.
	return result(map[string]any{"accounts": infos, "default_scope": aliases, "mode": modeInfo})
}

// --- mail_search ---

type searchArgs struct {
	Account       any    `json:"account,omitempty" jsonschema:"Mailbox alias, address, or a list of either. Omit to search every mailbox this grant allows."`
	Query         string `json:"query,omitempty" jsonschema:"Provider search syntax, for example Gmail's from:x is:unread"`
	From          string `json:"from,omitempty"`
	To            string `json:"to,omitempty"`
	Subject       string `json:"subject,omitempty"`
	Unread        bool   `json:"unread,omitempty"`
	Starred       bool   `json:"starred,omitempty"`
	HasAttachment bool   `json:"has_attachment,omitempty"`
	Limit         int    `json:"limit,omitempty" jsonschema:"Total results across all mailboxes, not per mailbox. Defaults to 25."`
	Cursor        string `json:"cursor,omitempty" jsonschema:"Continue a previous search. Only valid for the same set of mailboxes."`
}

func (t *Tools) handleSearch(ctx context.Context, _ *mcp.CallToolRequest, args searchArgs) (*mcp.CallToolResult, any, error) {
	g, err := requireGrant(ctx)
	if err != nil {
		return nil, nil, err
	}

	selector, err := parseSelector(args.Account)
	if err != nil {
		return t.invalid(ctx, g, grant.Audit{
			Tool: "mail.search", Capability: mail.CapRead,
		}, err), nil, nil
	}

	accounts, err := t.gate.Resolve(ctx, g, "mail.search", selector, mail.CapRead)
	if err != nil {
		return toolError(err), nil, nil
	}

	q := mail.Query{
		Raw: args.Query, From: args.From, To: args.To, Subject: args.Subject,
		Unread: args.Unread, Starred: args.Starred, HasAttach: args.HasAttachment,
		Limit: args.Limit,
	}

	res, err := aggregate.Fan(ctx, accounts, args.Cursor,
		aggregate.Options{Limit: args.Limit},
		func(m mail.Message) time.Time { return m.Date },
		func(m mail.Message) mail.AccountID { return m.ID.Account },
		func(ctx context.Context, acct mail.Account, cursor string) (mail.Page[mail.Message], error) {
			p, err := t.providers.For(ctx, acct)
			if err != nil {
				return mail.Page[mail.Message]{}, err
			}
			reader, ok := p.(mail.MessageReader)
			if !ok {
				return mail.Page[mail.Message]{}, &mail.UnsupportedError{
					Provider: p.ID(), Account: acct.Alias, Address: acct.Address,
					Capability: mail.CapRead,
				}
			}
			return reader.Search(ctx, q, cursor)
		})
	if err != nil {
		return toolError(err), nil, nil
	}

	// How many results each mailbox contributed. This is the whole of what a search records
	// about what it found, and the omission is deliberate: a search returns whatever matched,
	// so a row listing its result ids would be a list of everything in a mailbox matching a
	// query, written on every call. The count answers "how much", and the mail_get_message
	// row that follows names the message that was actually opened.
	found := map[mail.AccountID]int{}
	for _, m := range res.Items {
		found[m.ID.Account]++
	}

	// Every mailbox the search touched is recorded before any of it is handed over. A row
	// that cannot be written withholds the whole answer rather than part of it: the results
	// are already merged, and returning the rest would disclose exactly the mailbox whose
	// read went unrecorded.
	for _, acct := range accounts {
		reported := res.Accounts[acct.Alias]
		status := string(reported.Status)
		t.gate.Observe(ctx, g, acct.ID, status)
		if err := t.gate.Record(ctx, g, grant.Audit{
			AccountID: acct.ID, Tool: "mail.search", Outcome: status,
			// The per-account message is the reason a fan-out has: one mailbox can time out
			// while another answers, so the explanation belongs on that mailbox's own row
			// rather than on the call as a whole.
			Reason:     reported.Message,
			Capability: mail.CapRead, Affected: counted(found[acct.ID]),
		}); err != nil {
			return toolError(fmt.Errorf("this search was run, and its results are being withheld "+
				"because the read of %s could not be written to the audit log: %w", acct.Display(), err)), nil, nil
		}
	}

	// Every account failing is an error, not an empty inbox — and the per-account statuses
	// travel with it. Saying "see the statuses" while dropping them leaves a caller, and
	// whoever is debugging, with nothing to go on.
	if res.Failed() {
		return errorWithDetail("every mailbox failed", map[string]any{"accounts": res.Accounts}), nil, nil
	}

	return result(map[string]any{
		"results":  summarize(res.Items, accounts),
		"accounts": res.Accounts,
		"cursor":   res.Cursor,
		"complete": res.Complete,
	})
}

// --- single-message tools ---

type idArgs struct {
	ID string `json:"id" jsonschema:"Message or thread id from a search result. Opaque; pass it back unchanged."`
}

func (t *Tools) handleGetMessage(ctx context.Context, _ *mcp.CallToolRequest, args idArgs) (*mcp.CallToolResult, any, error) {
	g, err := requireGrant(ctx)
	if err != nil {
		return nil, nil, err
	}
	id, err := mail.ParseScopedID(args.ID)
	if err != nil {
		return t.invalid(ctx, g, grant.Audit{
			Tool: "mail.get_message", Capability: mail.CapRead,
		}, err), nil, nil
	}
	acct, err := t.gate.ResolveOne(ctx, g, "mail.get_message", id, mail.CapRead)
	if err != nil {
		return toolError(err), nil, nil
	}
	p, err := t.providers.For(ctx, acct)
	if err != nil {
		return toolError(err), nil, nil
	}
	reader, ok := p.(mail.MessageReader)
	if !ok {
		return toolError(&mail.UnsupportedError{
			Provider: p.ID(), Account: acct.Alias, Address: acct.Address, Capability: mail.CapRead,
		}), nil, nil
	}

	// The id, and nothing off the message. Which message was opened is the fact an operator
	// needs afterwards, and it survives the mail changing; the subject and the sender are the
	// mailbox's own content, and a log holding them for every read becomes a copy of it.
	msg, err := reader.Get(ctx, id)
	if err := t.auditRead(ctx, g, grant.Audit{
		AccountID: acct.ID, Tool: "mail.get_message", Capability: mail.CapRead,
		Affected: counted(1), Detail: grant.Detail{IDs: []string{id.String()}},
	}, err); err != nil {
		return toolError(err), nil, nil
	}
	return result(fullMessage(msg, acct))
}

func (t *Tools) handleGetThread(ctx context.Context, _ *mcp.CallToolRequest, args idArgs) (*mcp.CallToolResult, any, error) {
	g, err := requireGrant(ctx)
	if err != nil {
		return nil, nil, err
	}
	id, err := mail.ParseScopedID(args.ID)
	if err != nil {
		return t.invalid(ctx, g, grant.Audit{
			Tool: "mail.get_thread", Capability: mail.CapRead,
		}, err), nil, nil
	}
	acct, err := t.gate.ResolveOne(ctx, g, "mail.get_thread", id, mail.CapRead)
	if err != nil {
		return toolError(err), nil, nil
	}
	p, err := t.providers.For(ctx, acct)
	if err != nil {
		return toolError(err), nil, nil
	}
	reader, ok := p.(mail.ThreadReader)
	if !ok {
		return toolError(&mail.UnsupportedError{
			Provider: p.ID(), Account: acct.Alias, Address: acct.Address, Capability: mail.CapRead,
		}), nil, nil
	}

	thread, err := reader.GetThread(ctx, id)
	if err := t.auditRead(ctx, g, grant.Audit{
		AccountID: acct.ID, Tool: "mail.get_thread", Capability: mail.CapRead,
		Affected: counted(len(thread.Messages)), Detail: grant.Detail{IDs: []string{id.String()}},
	}, err); err != nil {
		return toolError(err), nil, nil
	}

	messages := make([]map[string]any, len(thread.Messages))
	for i, m := range thread.Messages {
		messages[i] = fullMessage(m, acct)
	}
	return result(map[string]any{
		"id":              thread.ID.String(),
		"account":         thread.Account,
		"account_address": acct.Address,
		"subject":         thread.Subject,
		"derived":         thread.Derived,
		"messages":        messages,
	})
}

type attachmentArgs struct {
	MessageID    string `json:"message_id"`
	AttachmentID string `json:"attachment_id"`
	Inline       bool   `json:"inline,omitempty" jsonschema:"Return the contents as text in this conversation instead of a link. Only for small text files whose wording you need — a note, a CSV, a log. Refused for anything larger than 64 KiB or anything that is not text; everything else comes back as a URL."`
}

// maxInlineDownload is the ceiling on the one path that still puts attachment content in the
// caller's context.
//
// It exists because there is a real case for it — a two-line .txt or a small .csv where the
// wording is the entire point, and a link means a round trip to learn six words — and it is
// small because that case is small. Anything above this is a file rather than a message, and
// a file is what the link is for. Note this is a download-side cap and has nothing to do with
// maxInlineAttachment, which bounds what the transport will carry in the other direction.
const maxInlineDownload = 64 << 10

func (t *Tools) handleGetAttachment(ctx context.Context, _ *mcp.CallToolRequest, args attachmentArgs) (*mcp.CallToolResult, any, error) {
	g, err := requireGrant(ctx)
	if err != nil {
		return nil, nil, err
	}
	id, err := mail.ParseScopedID(args.MessageID)
	if err != nil {
		return t.invalid(ctx, g, grant.Audit{
			Tool: "mail.get_attachment", Capability: mail.CapAttachments,
		}, err), nil, nil
	}
	acct, err := t.gate.ResolveOne(ctx, g, "mail.get_attachment", id, mail.CapAttachments)
	if err != nil {
		return toolError(err), nil, nil
	}
	p, err := t.providers.For(ctx, acct)
	if err != nil {
		return toolError(err), nil, nil
	}
	reader, ok := p.(mail.AttachmentReader)
	if !ok {
		return toolError(&mail.UnsupportedError{
			Provider: p.ID(), Account: acct.Alias, Address: acct.Address,
			Capability: mail.CapAttachments,
		}), nil, nil
	}

	// How the bytes left matters more than which file they were: `inline` puts them in the
	// caller's context, and a link puts them behind a signature somebody else may follow. The
	// filename is not recorded, on the same rule as a subject that was read — it is the
	// mailbox's own content, and this is the tool that pulls files out of one.
	how := "link"
	if args.Inline {
		how = "inline"
	}
	att, err := reader.GetAttachment(ctx, id, args.AttachmentID)
	if err := t.auditRead(ctx, g, grant.Audit{
		AccountID: acct.ID, Tool: "mail.get_attachment", Capability: mail.CapAttachments,
		Affected: counted(1),
		Detail:   grant.Detail{Action: how, IDs: []string{id.String()}},
	}, err); err != nil {
		return toolError(err), nil, nil
	}

	if args.Inline {
		return inlineAttachmentResult(att)
	}
	if t.blobs == nil {
		return toolError(fmt.Errorf("this server has no attachment storage configured, so it " +
			"cannot hand out a download link. Ask the operator to check MAILROOM_ATTACHMENT_DIR")), nil, nil
	}

	link, err := t.blobs.PutMailAttachment(ctx, blob.MailPut{
		Owner:     g.OwnerID,
		GrantID:   g.ID,
		AccountID: acct.ID,
		Filename:  att.Filename,
		MimeType:  att.MimeType,
		Content:   att.Content,
	})
	if err != nil {
		return toolError(err), nil, nil
	}
	return attachmentLinkResult(link)
}

// --- mail_upload_url ---

type uploadArgs struct {
	Filename  string `json:"filename" jsonschema:"Name the recipient will see on the attachment."`
	MimeType  string `json:"mime_type,omitempty" jsonschema:"Content type of the file, for example application/pdf. Defaults to application/octet-stream."`
	SizeBytes int64  `json:"size_bytes,omitempty" jsonschema:"How large the file is, if you know. It only ever narrows the ceiling this URL will accept."`
}

func (t *Tools) handleUploadURL(ctx context.Context, _ *mcp.CallToolRequest, args uploadArgs) (*mcp.CallToolResult, any, error) {
	g, err := requireGrant(ctx)
	if err != nil {
		return nil, nil, err
	}
	if t.blobs == nil {
		return toolError(fmt.Errorf("this server has no attachment storage configured, so it " +
			"cannot accept uploads. Ask the operator to check MAILROOM_ATTACHMENT_DIR")), nil, nil
	}
	if args.Filename == "" {
		return t.invalid(ctx, g, grant.Audit{Tool: "mail.upload_url"},
			fmt.Errorf("an upload needs a filename: it is the name the recipient sees")), nil, nil
	}

	upload, err := t.blobs.NewUpload(ctx, blob.UploadRequest{
		Owner:    g.OwnerID,
		GrantID:  g.ID,
		Filename: args.Filename,
		MimeType: args.MimeType,
		MaxBytes: args.SizeBytes,
	})
	if err != nil {
		return toolError(err), nil, nil
	}

	// No mailbox is touched by minting one of these, so there is no per-account read to
	// record. It is still worth a row: it is the moment a grant was given somewhere to write.
	// The filename is the client's own — it named a file it holds, not one of the operator's
	// — and it is the only thing that makes this row worth reading later, beside the send it
	// turns up in.
	if note := t.auditChange(ctx, g, grant.Audit{
		Tool: "mail.upload_url", Detail: grant.Detail{Name: args.Filename},
	}, nil); note != "" {
		return result(noted(uploadPayload(upload), note))
	}
	return result(uploadPayload(upload))
}

// uploadPayload answers with both of the deadlines an upload has, because they are different
// and a client that conflates them gets one of two wrong answers.
//
// `expires_at` is the URL's, beside the URL it describes and matching what every other
// `expires_at` in this API means: when the thing next to it stops working. It used to be the
// blob's, which is the longer of the two and is capped by nothing shorter than
// MAILROOM_ATTACHMENT_TTL — so a client on an instance configured for a day was told it had a
// day to perform a PUT the signature would refuse after ten minutes.
//
// `blob_expires_at` is the other one, and it is worth returning rather than dropping: it is
// how long the blob_id stays worth naming in a message once the bytes are up.
func uploadPayload(u blob.Upload) map[string]any {
	return map[string]any{
		"upload_url":      u.URL,
		"method":          u.Method,
		"blob_id":         u.ID,
		"filename":        u.Filename,
		"max_bytes":       u.MaxBytes,
		"expires_at":      u.URLExpires.UTC().Format(time.RFC3339),
		"blob_expires_at": u.ExpiresAt.UTC().Format(time.RFC3339),
		"how": "PUT the file's bytes to upload_url as the raw request body, with no " +
			"authorization header. The URL works once, and stops working at expires_at. Then " +
			"attach it by passing {\"blob_id\": \"" + u.ID + "\"} in the attachments list of " +
			"mail_draft or mail_send, any time before blob_expires_at.",
	}
}

// --- holding ---

// outcomeHeld is the audit outcome for a call that was recorded instead of performed. It is
// neither a success nor a refusal and the audit page treats it as its own thing: nothing was
// done, and nothing was turned away either.
const outcomeHeld = "held"

// hold records a privileged call for its owner to answer, instead of performing it, and
// answers the client with a result that says so in as many ways as a result can.
//
// It is called after the grant has authorized the call and after everything that could still
// fail on its own — the provider being reachable, the attachments resolving — so that the
// queue holds instructions that will work rather than requests that might. A caller refused
// on capability is refused, not queued.
//
// The nil check fails the call closed. A grant whose mode says hold, on a server with nowhere
// to hold anything, must not quietly perform the action instead: that is the exact shape of
// "the safe path was unavailable, so we took the unsafe one", and it is the shape this whole
// mode exists to avoid.
func (t *Tools) hold(ctx context.Context, g *grant.Grant, acct mail.Account, e grant.Audit,
	kind held.Kind, summary string, payload any) (map[string]any, error) {

	if t.holds == nil {
		return nil, fmt.Errorf(
			"this connection holds privileged actions for the owner of %s to approve, and "+
				"this server has nowhere to hold them, so nothing was done and nothing was "+
				"queued", acct.Alias)
	}

	action, err := t.holds.Hold(ctx, g, acct, e.Tool, kind, summary, payload)
	if err != nil {
		return nil, err
	}

	// The row the call would have written, with an outcome of its own. It carries everything
	// the performed call would have carried — the recipients, the subject, the ids — because
	// what the client asked for is the fact worth recording at the moment it asked, rather
	// than only when somebody gets round to answering it. A held send marked `ok` would read,
	// months later, as mail that went out.
	e.Outcome = outcomeHeld
	note := ""
	if rec := t.gate.Record(ctx, g, e); rec != nil {
		note = "this action is waiting for approval but could not be written to the audit log: " + rec.Error()
	}

	result := map[string]any{
		"held":            true,
		"action_id":       action.ID,
		"account":         acct.Alias,
		"account_address": acct.Address,
		"waiting_for":     summary,
		"approve_at":      t.holdURL,
		"note": "Nothing was done. This connection is set to hold privileged actions, so the " +
			"call above is queued for the owner of " + acct.Alias + " to approve or discard " +
			"at " + t.holdURL + ". Tell whoever you are working with that it is waiting for " +
			"approval; do not report it as done, and do not call this again to retry.",
	}
	// When it stops waiting. A client told only that something is queued will go on saying so
	// for as long as it is asked, which stops being true the moment the action expires — and
	// this is the one fact about the queue the far end cannot look up for itself.
	if ttl := t.holds.TTL(); ttl > 0 {
		result["expires_at"] = action.CreatedAt.Add(ttl).UTC().Format(time.RFC3339)
	}
	return noted(result, note), nil
}

// heldResult is the whole of a tool's answer when its call was held. The tools that group by
// mailbox use hold directly instead, because each of their mailboxes gets its own row in a
// single result.
func (t *Tools) heldResult(ctx context.Context, g *grant.Grant, acct mail.Account, e grant.Audit,
	kind held.Kind, summary string, payload any) (*mcp.CallToolResult, any, error) {

	body, err := t.hold(ctx, g, acct, e, kind, summary, payload)
	if err != nil {
		return toolError(err), nil, nil
	}
	return result(body)
}

func outcome(err error) string {
	if err != nil {
		return mail.Code(err)
	}
	return "ok"
}

// auditRead records a call whose result has not reached the caller yet, and refuses to hand
// that result over when the row cannot be written.
//
// Refusing is worth something here, which is the whole reason the two audit helpers differ:
// the mailbox has been read but nothing has been disclosed, so withholding the answer is
// what keeps "no mailbox is read unrecorded" true rather than aspirational. A read that
// failed on its own is reported as itself — there is no content to withhold, and the
// provider's error is the one that helps.
func (t *Tools) auditRead(ctx context.Context, g *grant.Grant, e grant.Audit, callErr error) error {
	e = settled(e, callErr)
	t.gate.Observe(ctx, g, e.AccountID, e.Outcome)
	rec := t.gate.Record(ctx, g, e)
	if callErr != nil || rec == nil {
		return callErr
	}
	return fmt.Errorf("this mailbox was read, and the result is being withheld because the "+
		"read could not be written to the audit log: %w", rec)
}

// auditChange records a call that has already changed a mailbox, and returns a note when the
// row could not be written.
//
// It cannot refuse, and that is not a compromise. By the time the row is written the message
// is sent and the labels are applied; the accountability is already lost, and an error would
// only report a failure that did not happen and invite a retry that does the work twice. All
// that is left is to say in the result that the change went unrecorded, rather than to
// discard the fact.
func (t *Tools) auditChange(ctx context.Context, g *grant.Grant, e grant.Audit, callErr error) string {
	e = settled(e, callErr)
	t.gate.Observe(ctx, g, e.AccountID, e.Outcome)
	if err := t.gate.Record(ctx, g, e); err != nil {
		return "this call changed the mailbox but could not be written to the audit log: " + err.Error()
	}
	return ""
}

// invalid records a call this server refused on the arguments it arrived with, and renders
// the refusal.
//
// These reach no mailbox and used to write nothing at all, so a client sending malformed
// calls all day was invisible on the one page that exists to say what a client has been
// doing. They are marked with an outcome of their own rather than folded in with the mail
// error codes, because a client with a bug and a mailbox with a problem are different things
// to go and look at.
//
// The write failure is dropped, for the reason the gate drops its own: nothing was disclosed,
// so there is no answer to withhold, and replacing the explanation the caller needs with one
// about bookkeeping helps nobody.
func (t *Tools) invalid(ctx context.Context, g *grant.Grant, e grant.Audit, err error) *mcp.CallToolResult {
	e.Outcome, e.Reason = grant.OutcomeInvalid, err.Error()
	_ = t.gate.Record(ctx, g, e)
	return toolError(err)
}

// settled fills in the half of an entry that follows from how the call ended, so no caller
// has to keep an outcome and a reason in step by hand. A reason is written only on a failure:
// it is the sentence the client was given, and a call that worked was given none.
func settled(e grant.Audit, callErr error) grant.Audit {
	e.Outcome = outcome(callErr)
	if callErr != nil {
		e.Reason = callErr.Error()
	}
	return e
}

// counted is how a tool says "this many", where zero is a measurement rather than a default.
func counted(n int) *int { return &n }

// scopedIDs renders a batch of ids for an audit entry. The store bounds the list; this only
// turns it into the strings that still identify a message after the mailbox has moved on.
func scopedIDs(ids []mail.ScopedID) []string {
	out := make([]string, len(ids))
	for i, id := range ids {
		out[i] = id.String()
	}
	return out
}

// recipients lists the addresses a call directed mail to.
//
// Addresses only, never the display name beside one: the address is what says where mail
// actually went, and the name is whatever the caller chose to type next to it.
func recipients(in []addressArg) []string {
	out := make([]string, 0, len(in))
	for _, a := range in {
		out = append(out, a.Email)
	}
	return out
}

// noted attaches an unwritten-audit warning to a successful result, so a caller sees that
// what it asked for happened and was not recorded.
func noted(payload map[string]any, note string) map[string]any {
	if note != "" {
		payload["not_recorded"] = note
	}
	return payload
}

func asScope(err error, target **mail.ScopeError) bool { return errors.As(err, target) }
