#!/usr/bin/env bash
# Sets up everything mailroom needs. Google publishes no API for OAuth clients, so creating
# the consent screen and the client stays a Console step; the redirect URIs on it do not,
# because Terraform drives the Console for those. See deploy/terraform/google/README.md for
# what every other route returned and why none of them work.
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-}"
PUBLIC_URL="${PUBLIC_URL:-http://localhost:8080}"
ENV_FILE="${ENV_FILE:-.env}"
BIN="${BIN:-go run ./cmd/mailroom}"

die() { echo "error: $*" >&2; exit 1; }
step() { printf '\n\033[1m%s\033[0m\n' "$*"; }

[ -n "$PROJECT_ID" ] || die "set PROJECT_ID=your-gcp-project-id"

step "1/6  Checking which identity Terraform will use"
# The Google provider reads Application Default Credentials, not the gcloud CLI account.
# Applying with the wrong one creates the project under that account — and inside its
# organization — with no error at all.
ADC_EMAIL=$(gcloud auth application-default print-access-token 2>/dev/null |
  xargs -I{} curl -s -H "Authorization: Bearer {}" \
    https://www.googleapis.com/oauth2/v1/userinfo 2>/dev/null |
  sed -n 's/.*"email": *"\([^"]*\)".*/\1/p') || true

if [ -z "${ADC_EMAIL:-}" ]; then
  die "no Application Default Credentials. Run: gcloud auth application-default login"
fi
echo "    Terraform will act as: $ADC_EMAIL"
read -r -p "    Is that the right account? [y/N] " ok
[ "$ok" = "y" ] || die "run 'gcloud auth application-default login' and pick the right account"

step "2/6  Creating the project and enabling the Gmail API"
terraform -chdir=deploy/terraform/google init -input=false >/dev/null
# The account just confirmed becomes the assertion Terraform enforces on every later run, so
# a machine whose ADC drifts to a work account fails instead of creating something there.
terraform -chdir=deploy/terraform/google apply -input=false -auto-approve \
  -var "project_id=$PROJECT_ID" -var "google_account=$ADC_EMAIL" >/dev/null
echo "    Gmail API enabled on $PROJECT_ID"

step "3/6  The part with no API — creating the client"
cat <<EOF

    a) Consent screen:
       https://console.cloud.google.com/auth/overview?project=$PROJECT_ID

       Choose External. While the app is in Testing, add every mailbox you intend
       to link as a test user, or linking fails with access_denied. Note that a
       Testing app's refresh tokens expire after seven days.

    b) OAuth client:
       https://console.cloud.google.com/auth/clients?project=$PROJECT_ID

       Type: Web application. Leave the redirect URIs empty — the next step
       registers both of them, and getting them exactly right is the part that
       used to go wrong.

EOF
read -r -p "    Paste the client ID: " CLIENT_ID
read -r -s -p "    Paste the client secret: " CLIENT_SECRET; echo
[ -n "$CLIENT_ID" ] && [ -n "$CLIENT_SECRET" ] || die "both values are required"

step "4/6  Registering the redirect URIs"
cat <<EOF
    This part is yours, and it is the only step that is. Google publishes no API
    for it — not Terraform, not gcloud — so on the same Console page, under
    Authorized redirect URIs, add both of these to the client you just made:

        ${PUBLIC_URL}/accounts/link/google/callback
        ${PUBLIC_URL}/auth/google/callback

    The first links a Gmail mailbox, the second signs you in, and Google matches
    them character for character. Registering only the first gives you an instance
    that links mailboxes perfectly and cannot be logged into.

    Nothing here has to trust that you did it: 'mailroom doctor' asks Google
    directly and names whichever one is missing.
EOF

step "5/6  Generating the encryption key"
ENCRYPTION_KEY=$(openssl rand -base64 32)
echo "    Done. There is no operator password to choose: you sign in with the Google"
echo "    account this OAuth client belongs to."

step "6/6  Writing $ENV_FILE"
umask 077

# SQLite opens a database file but will not create the directory holding it, and ./data is
# gitignored, so a fresh clone has none. Without this the first start fails with "unable to
# open database file (14)", which names neither the directory nor the fix. The directory ends
# up holding sealed mailbox credentials, so it is created private rather than world-readable.
mkdir -p ./data
chmod 700 ./data
# Every value is single-quoted. These are generated and pasted secrets rather than values
# chosen here, so any of them may contain $, a backtick or a space; sourcing this file
# unquoted would let the shell expand or split those, silently delivering a truncated
# secret and a failure that points nowhere near this file.
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh. Contains secrets — never commit this file.
MAILROOM_PUBLIC_URL='$PUBLIC_URL'
MAILROOM_DB='sqlite://./data/mailroom.db'

# Seals stored mailbox credentials. BACK THIS UP somewhere other than this host:
# without it every linked mailbox must be re-linked.
MAILROOM_ENCRYPTION_KEY='$ENCRYPTION_KEY'

# Sign in with Google. This costs no extra credentials: the issuer is known, and the
# login falls back to the MAILROOM_GOOGLE_CLIENT_* pair below. It does require
# ${PUBLIC_URL}/auth/google/callback to be registered at Google, alongside the linking
# URI — the two paths differ and Google matches exactly.
MAILROOM_AUTH_PROVIDERS='google'

# Who may create an account here: closed, invite, allowlist or open. Closed admits
# nobody new — the first sign-in claims the instance and everyone after it is refused.
# Anything looser is only safe once an identity provider in front decides membership.
MAILROOM_SIGNUPS='closed'

MAILROOM_GOOGLE_CLIENT_ID='$CLIENT_ID'
MAILROOM_GOOGLE_CLIENT_SECRET='$CLIENT_SECRET'
EOF

# Prove the file round-trips before claiming success. A secret the shell mangled on the way
# back in fails much later, at a sign-in or a link, with a message that blames Google.
LOADED=$(set -a; . "./$ENV_FILE"; set +a;
  printf '%s\n%s' "$MAILROOM_ENCRYPTION_KEY" "$MAILROOM_GOOGLE_CLIENT_SECRET")
[ "$LOADED" = "$(printf '%s\n%s' "$ENCRYPTION_KEY" "$CLIENT_SECRET")" ] ||
  die "the generated $ENV_FILE does not round-trip: a value changed when sourced"
chmod 600 "$ENV_FILE"

cat <<EOF

    Done. Start it with:

        set -a; . ./$ENV_FILE; set +a
        $BIN

    Then open $PUBLIC_URL and sign in with Google. That first sign-in claims the
    instance; nobody else can create an account until you choose a signup policy.
    Link a mailbox from there.

    Back up MAILROOM_ENCRYPTION_KEY now, somewhere that does not depend on this host.

EOF
